### ISSUE TITLE
Missing exports

### ISSUE THREAD

**Issue by Serial-ATA** [uklotzde/mpeg-audio-header#1]
`Header` is not fully usable, since some of the types were not exported.

https://github.com/uklotzde/mpeg-audio-header/blob/fe349f1c91867ecd39421f71bcdb10b30760f881/src/lib.rs#L32

This should probably be a `pub use` :)

https://github.com/uklotzde/mpeg-audio-header/blob/fe349f1c91867ecd39421f71bcdb10b30760f881/src/lib.rs#L53-L66

These are the fields effected

**Comment by uklotzde** [comment]
Ouch, thanks or reporting. I wonder why this didn't trigger any warnings. Will check soon. I only needed the numerical values for my use case.

**Comment by uklotzde** [comment]
v0.0.2: 55c550e8d54a22c45732c4bba37086ca63be3442
